extends: eslint:recommended
env:
  node: true
  browser: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
  no-empty:
    - error
    - allowEmptyCatch: true

  react/jsx-uses-react: error
  react/jsx-uses-vars: error
